name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./TP2
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Exemplo A 01
      run: |
        python3 main.py --input exemplos/exemplo-A-01.fca
    - name: Exemplo B 01
      run: |
        python3 main.py --input exemplos/exemplo-B-01.fca
    - name: Exemplo B 02
      run: |
        python3 main.py --input exemplos/exemplo-B-02.fca
    - name: Exemplo B 03
      run: |
        python3 main.py --input exemplos/exemplo-B-03.fca < "Olá, mundo!"
    - name: Exemplo C 01
      run: |
        python3 main.py --input exemplos/exemplo-C-01.fca
    - name: Exemplo C 02
      run: |
        python3 main.py --input exemplos/exemplo-C-02.fca
    - name: Exemplo C 03
      run: |
        python3 main.py --input exemplos/exemplo-C-03.fca
    - name: Exemplo C 04
      run: |
        python3 main.py --input exemplos/exemplo-C-04.fca
    - name: Exemplo D 01
      run: |
        python3 main.py --input exemplos/exemplo-D-01.fca
    - name: Exemplo D 02
      run: |
        python3 main.py --input exemplos/exemplo-D-02.fca
    - name: Exemplo D 02b
      run: |
        python3 main.py --input exemplos/exemplo-D-02b.fca
    - name: Exemplo D 03
      run: |
        python3 main.py --input exemplos/exemplo-D-03.fca